fix(move-mail): #MZI-192 fix move mail from parent to a sub folder
OPEN-ENT-NG/zimbra-connector pull request #104
Opened 2023-09-04 15:18 UTC by Alex-Delaveau

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-09-05 11:51 UTC, JinDouang requested changes

2023-09-05 11:51 UTC, JinDouang commented on zimbra/src/main/resources/public/ts/controllers/controller.ts
> +        $scope.isCurrentFolderMove = (folder: UserFolder, obj) => {
ton nommage induit que ça retourne un boolean alors qu'en réalité tu fais une action en fonction de ta condition

Tu devrais revoir ton nommage de la fonction

2023-09-05 11:51 UTC, JinDouang commented on zimbra/src/main/resources/public/ts/controllers/controller.ts
> +        $scope.isCurrentFolderMove = (folder: UserFolder, obj) => {
Tu peux typer ton obj, visiblement c'est : 

```
{ template: string }
```

2023-09-05 15:50 UTC, JinDouang approved these changes

2023-09-06 14:52 UTC, FlorentMr approved these changes

2023-09-06 15:15 UTC, merged