fix(image): #MZI-212 fix external image in mail body
OPEN-ENT-NG/zimbra-connector pull request #106
Opened 2023-09-14 10:04 UTC by Alex-Delaveau

## Describe your changes
Fix issue where images in mail body from external senders where not displayed in zimbra but were displayed in expert mode
## Checklist tests
Send a mail from another client (Outlook, Thunderbird...) with a image in body (Copy/Paste it into the mail not attachement). Then in Zimbra check if the image is displayed correctly.  
## Issue ticket number and link
[MZI-212](https://jira.support-ent.fr/browse/MZI-212)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-09-18 08:02 UTC, JinDouang requested changes

2023-09-18 08:02 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/data/HttpService.java
> +        HttpClient httpClient = HttpClientHelper.createHttpClient(vertx);
Pourquoi ne pas utiliser WebClient ?

2023-09-18 08:02 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +            this.zimbraUrlGetImage = Zimbra.appConfig.getZimbraUri() + "/service/home/~/?auth=co&loc=fr_FR&id=";
D'où vient cet endpoint?

2023-09-18 08:02 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +                    log.error("Zimbra@transformMessageZimbraToFront : error transforming messages: " + error.getMessage());
Nécessaire de faire en 2 lignes ?
Tu peux ne pas utiliser ar.cause().getMessage() directement ?

Et malgré la "gestion" d'erreur, tu continues l'instruction

2023-09-18 08:02 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +                log.error("Zimbra@processMessageMultipart : error processing multiparts: " + error.getMessage());
Tu peux faire directement en ar.cause().getMessage()

2023-09-18 08:02 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +    private Future<JsonObject> replaceCidToUrl(Multipart  mparts, JsonObject msgFront, UserInfos user) {
Je veux bien que tu détailles ton opération et le cid qu'est-ce que tu fais exactement ?

2023-09-18 08:40 UTC, qpic-cgi requested changes

2023-09-18 08:40 UTC, qpic-cgi commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +        replaceCidToUrl(mparts, msgFront, user).onComplete(ar -> {
.onSuccess(...)
.onFailure(...)

2023-09-18 08:40 UTC, qpic-cgi commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +                promise.fail(error);
ne remonte pas la stacktrace, remonte ton message plutôt:
```suggestion
                String message = String.format("[Zimbra@%s::processMessageMultipart ] Fail to store " +
                                            "permissions preferences to session. %s", this.getClass().getSimpleName()));
                log.error(String.format("%s %s", message, error.getMessage());
                promise.fail(message);
```

2023-09-22 07:11 UTC, JinDouang requested changes

2023-09-22 07:11 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/helper/CidHelper.java
> +            return new ArrayList<>();
tu devrais rajouter log erreur

2023-09-22 07:11 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/helper/CidHelper.java
> +            Pattern pattern = Pattern.compile(Zimbra.appConfig.getZimbraDocumentConfig().getString("zimbraCidPattern"));
const ?

2023-09-22 07:11 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/helper/ConfigManager.java
> +    private final JsonObject zimbraDocumentConfig;
tu pouvais pas le modéliser ?

2023-09-22 07:11 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/helper/CidHelper.java
> +            Pattern pattern = Pattern.compile(Zimbra.appConfig.getZimbraDocumentConfig().getString("zimbraCidPattern"));
tu pouvais pas le modéliser ?

2023-09-22 07:11 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/helper/CidHelper.java
> +        String zimbraUrlGetImage = Zimbra.appConfig.getZimbraUri() + Zimbra.appConfig.getZimbraDocumentConfig().getString("zimbraDocumentEndpoint");;
tu pouvais pas le modéliser ?

2023-09-22 07:11 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/helper/CidHelper.java
> +        int partCount = 2;
pourquoi 2 ?

peux-tu éclaircir ton raisonnement dans ta boucle ?

2023-09-22 07:11 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/helper/ConfigManager.java
> +        this.zimbraDocumentConfig = config.getJsonObject("zimbra-document-config", new JsonObject()
tu pouvais pas le modéliser ?

2023-09-22 07:11 UTC, JinDouang commented on zimbra/src/test/java/fr/openent/zimbra/helper/CidHelperTest.java
> +    public void testGetCids (TestContext ctx) {
précise ce que ton TU est censé faire en terme de nommage

2023-09-26 17:31 UTC, JinDouang approved these changes

2023-09-27 07:59 UTC, merged