feat(migration): #MZI-241 migration Vertx
OPEN-ENT-NG/zimbra-connector pull request #111
Opened 2024-08-30 12:06 UTC by Glama107

## Describe your changes

Migration de Vertx 3 vers Vertx 4

## Checklist tests

## Issue ticket number and link

https://jira.support-ent.fr/browse/MZI-241

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-08-30 14:16 UTC, Alex-Delaveau requested changes

2024-08-30 14:16 UTC, Alex-Delaveau commented on zimbra/src/main/java/fr/openent/zimbra/filters/AccessibleDocFilter.java
> +        for (String groupId : user.getGroupsIds()) {
Utilisation de Stream plutot que la boucle : 
```
Bson subQuery = Filters.or(
    Filters.eq("userId", user.getUserId()),
    Filters.or(user.getGroupsIds().stream()
        .map(groupId -> Filters.eq("groupId", groupId))
        .toArray(Bson[]::new))
);
```

2024-08-30 14:16 UTC, Alex-Delaveau commented on zimbra/src/main/java/fr/openent/zimbra/helper/PromiseHelper.java
> +    public static <T> Handler<Either<String, T>> handlerJsonObject(Promise<T> promise, String errorMessage) {
errorMessage est il vraiment utile ? Utiliser un Optional?

2024-08-30 14:16 UTC, Alex-Delaveau commented on zimbra/src/main/java/fr/openent/zimbra/service/data/SoapZimbraService.java
> +            String finalUrl = Boolean.TRUE.equals(params.getBoolean(PARAM_ISADMIN)) ? zimbraAdminUri : zimbraUri;
Cela ne sert à rien de tester si true == true : 
`Boolean.TRUE.equals(params.getBoolean(PARAM_ISADMIN))`

2024-08-30 14:16 UTC, Alex-Delaveau commented on zimbra/src/main/java/fr/openent/zimbra/service/data/SoapZimbraService.java
> +            if (Boolean.TRUE.equals(params.getBoolean(PARAM_IS_AUTH, true)) && params.containsKey(PARAM_AUTH_TOKEN)) {
test true == true inutile

2024-08-30 14:35 UTC, Alex-Delaveau approved these changes

2024-09-03 12:30 UTC, qperie approved these changes

2024-09-03 12:30 UTC, qperie commented on zimbra/src/main/java/fr/openent/zimbra/Zimbra.java
> +        startPromise.tryFail("[Zimbra@Zimbra::start] Fail to start ApiZimbra");
```suggestion
        startPromise.tryFail("[Zimbra@Zimbra::start] Fail to start Zimbra");
```

2024-09-03 12:58 UTC, merged