chore() : [MZI]add git action workflow ci and unit test
OPEN-ENT-NG/zimbra-connector pull request #21
Opened 2022-05-06 15:37 UTC by adrienFro

Implementation of UnitTest and add git action workflow
FRONT : group.test.ts
BACK : ZimbraAdminServiceTest.java

2022-05-09 09:05 UTC, Sofianebernoussi commented on zimbra/src/test/java/fr/openent/zimbra/service/test/impl/ZimbraAdminServiceTest.java
> +            queryParams.remove("roleId");
magic key x2

2022-05-09 09:07 UTC, JinDouang commented on zimbra/src/test/java/fr/openent/zimbra/service/test/impl/ZimbraAdminServiceTest.java
> +            queryParams.remove("roleId");
pour les fichiers TU, c'est pas nécessaire (limite mieux pour la lisibiltié du code)

2022-05-23 14:59 UTC, JinDouang requested changes

2022-05-23 14:59 UTC, JinDouang commented on zimbra/src/main/resources/public/ts/model/__test__/group.test.ts
> +            expect(data).toEqual(data);
ca devrait être response.data

2022-05-23 14:59 UTC, JinDouang commented on zimbra/src/main/resources/public/ts/model/__test__/group.test.ts
> +            expect(spy).toHaveBeenCalled();
on ne sait pas avec quoi ça devrait être appelé

2022-05-23 14:59 UTC, JinDouang commented on zimbra/src/test/java/fr/openent/zimbra/service/test/impl/ZimbraAdminServiceTest.java
> +        String expectedQuery = " MATCH (w:Action{name:{actionName}}) "
Aucune sens, tu testes la même chose...

2022-05-23 15:00 UTC, sjollois commented on gradle.properties
> +entCoreVersion=4.3.1
laisser la version 4.4-SNAPSHOT sur la branche dev

2022-05-25 08:39 UTC, JinDouang requested changes

2022-05-25 08:39 UTC, JinDouang commented on zimbra/src/main/resources/public/ts/model/__test__/group.test.ts
> +        const data = {"id": "2", "name": "GroupB", "nbUsers": 1, "isGroup": true};
tu peux pas utiliser le spy ?

2022-05-25 12:47 UTC, JinDouang approved these changes

2022-05-25 12:48 UTC, JinDouang approved these changes

2022-05-25 12:49 UTC, JinDouang commented on zimbra/src/main/resources/public/ts/model/__test__/group.test.ts
> +    group.id = undefined;
pas nécessaire

2022-05-25 13:34 UTC, merged