fix: #MZI-131 fix status for returned mail with 0 recipient
OPEN-ENT-NG/zimbra-connector pull request #36
Opened 2023-01-02 12:57 UTC by Matiyeu

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-02 13:50 UTC, sjollois approved these changes

2023-01-03 15:02 UTC, JinDouang requested changes

2023-01-03 15:02 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/ReturnedMailService.java
> +                        handler.handle(new Either.Left<>("[Zimbra] deleteMailFromZimbra : Error when moving to trash : " + ids.get(0)));
A mettre dans log.error (base toi sur ton log error que tu avais fait la dernière fois avec gar-connector)

utilise le Either.Left avec `moveToTrash.left.getValue`

2023-01-03 15:02 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/ReturnedMailService.java
> +                                handler.handle(new Either.Left<>("[Zimbra] deleteMailFromZimbra : Error when deleting mails : " + event.left().getValue()));
A mettre dans log.error (base toi sur ton log error que tu avais fait la dernière fois avec gar-connector)

utilise le Either.Left avec event.left.getValue

2023-01-03 15:05 UTC, JinDouang requested changes

2023-01-03 15:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/ReturnedMailService.java
> +        if (userIds.size() == 0) {
Vérifie si c'est null et puis tu as la méthode `isEmpty`

```suggestion
        if (userIds == null || userIds.isEmpty()) {
```

2023-01-03 17:24 UTC, JinDouang approved these changes

2023-01-03 17:24 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/ReturnedMailService.java
> +                                handler.handle(new Either.Left<>(String.format("[Zimbra@%s::deleteMailFromZimbra] Error when deleting mails: %s", this.getClass().getSimpleName(), event.left().getValu
Pas besoin d'envoyer le même log dans le handler, mets seulement le getValue
Les logs avec le format etc est plus pour les logs de vertx

```suggestion
                                                               handler.handle(event.left().getValue());

```

2023-01-04 09:52 UTC, aymericdevriesere approved these changes

2023-01-04 10:14 UTC, merged