fix: #MZI-109 encode folder path for uri, fix npe when folder does not exist
OPEN-ENT-NG/zimbra-connector pull request #40
Opened 2023-01-06 16:23 UTC by Matiyeu

## Describe your changes

* Encode the folder paths for uri
* Fix NPE when folder does not exist (GET /zimbra/list)

## Checklist tests

Front:
1. Create folder with special character (ex: t#est)
2. Open folder

Back:
1. Test GET/zimbra/list?folder=/Inbox/invalidpath => returns an empty array instead of a pending request

## Issue ticket number and link

[#MZI-109](https://jira.support-ent.fr/browse/MZI-109)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-06 16:30 UTC, JinDouang requested changes

2023-01-06 16:30 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                        renderJson(request, new JsonArray());
Donc si t'as une erreur, t'envoie quand même une réponse "ok" avec un json ?
log error ?

2023-01-09 07:38 UTC, sjollois requested changes
même remarque que Jin

2023-01-09 08:52 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                        renderJson(request, new JsonArray());
J'avais fail mon force push

2023-01-09 08:56 UTC, sjollois approved these changes

2023-01-09 11:33 UTC, JinDouang approved these changes

2023-01-09 11:34 UTC, merged