feat(calendar) : #MZI-105 get ical from zimbra api
OPEN-ENT-NG/zimbra-connector pull request #44
Opened 2023-01-10 14:42 UTC by alicedraillard

## Describe your changes
get ICal via Soap API request

## Checklist tests

## Issue ticket number and link
[MZI-105](https://jira.support-ent.fr/browse/MZI-105)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-10 15:36 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/CalendarService.java
> +                .put("_jsns", SoapConstants.NAMESPACE_MAIL);
```suggestion
                .put(Field._JSNS, SoapConstants.NAMESPACE_MAIL);
```

2023-01-10 15:49 UTC, qpic-cgi commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                                        //TODO send formatted ical back
Pourquoi laisser des todo ?
Pourquoi ne pas traiter la réponse ? cet endpoint n'est pas utilisable en l"état.

2023-01-10 15:53 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                                        //TODO send formatted ical back
les todos correspondent à des tickets futurs (de la même évo), la logique a été divisée afin de ne pas avoir des pr trop longues

2023-01-10 15:57 UTC, qpic-cgi commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                                        //TODO send formatted ical back
ok ça marche

2023-01-10 15:57 UTC, qpic-cgi approved these changes

2023-01-10 16:03 UTC, Matiyeu approved these changes

2023-01-10 16:04 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/model/soap/model/SoapICalResponse.java
> +    public SoapICalResponse(JsonObject icalSoapResponse) {
Vu avec Alice pour ajoute l'interface IModel

2023-01-10 16:04 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/model/soap/model/SoapICalResponse.java
> +    public JsonObject toJson() {
Vu avec @alicedraillard ajouter @override

2023-01-10 16:09 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/CalendarService.java
> +            icalRequest.put("s", rangeStart);
optional parameters https://files.zimbra.com/docs/soap_api/8.8.15/api-reference/zimbraMail/GetICal.html

2023-01-10 16:09 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/CalendarService.java
> +            icalRequest.put("e", rangeEnd);
optional parameters https://files.zimbra.com/docs/soap_api/8.8.15/api-reference/zimbraMail/GetICal.html

2023-01-10 16:11 UTC, BastienBenard approved these changes

2023-01-10 16:11 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/CalendarService.java
> +public class CalendarService {
Pour respecter la convention, tu peux crée une interface CalendarService et renommé cette classe en CalendarServiceImpl. Ensuite, il faut que tu deplace la java doc dans l'interface.

2023-01-10 16:11 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/CalendarService.java
> +                log.error(getICalResponse.left().getValue());
Format du message d'erreur incorrecte [SupportPivot@CalendarService::getICal] ... etc

2023-01-10 16:12 UTC, BastienBenard reviewed
Voir les commentaires du dessus

2023-01-10 16:31 UTC, sjollois requested changes

2023-01-10 16:31 UTC, sjollois commented on zimbra/src/main/java/fr/openent/zimbra/model/soap/model/SoapICalResponse.java
> +        this.content = this.ical.getJsonObject(0).getString(Field._CONTENT);
index out of bound exception possible !

2023-01-11 11:08 UTC, BastienBenard approved these changes

2023-01-11 11:08 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/CalendarServiceImpl.java
> +                .put(Field.CONTENT, icalRequest);
A voir si on ne peut pas plus tard crée un model. MAis ce sera pour un autre ticket

2023-01-11 13:59 UTC, sjollois commented on zimbra/src/main/java/fr/openent/zimbra/model/soap/model/SoapICalResponse.java
> +        this.content = this.ical.size() != 0 ? this.ical.getJsonObject(0).getString(Field._CONTENT) : "";
il manque une valeur par défaut dans le getString

2023-01-11 13:59 UTC, sjollois approved these changes

2023-01-11 14:10 UTC, merged