feat(calendar) : #MZI-113 format ical
OPEN-ENT-NG/zimbra-connector pull request #55
Opened 2023-01-18 10:19 UTC by alicedraillard

## Describe your changes
ical is formatted and sent back to Calendar module

## Checklist tests

## Issue ticket number and link
[MZI-113](https://jira.support-ent.fr/browse/MZI-113)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-18 10:21 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                                        ical = ical.replaceAll("\\\r\\\n", "\n");
implement line return

2023-01-18 10:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                                        ical = ical.replaceAll(";TZID\\=.*\\/.*\\\"", "");
remove `;TZID=\"Europe/Brussels\"` from ical (timezone will be treated in [MC-279](https://jira.support-ent.fr/browse/MC-279) )

2023-01-18 10:38 UTC, sjollois approved these changes

2023-01-19 10:24 UTC, qpic-cgi commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                    message.reply(new JsonObject().put(Field.STATUS, Field.ERROR).put(Field.MESSAGE, "zimbra.user.not.valid"));
simple suggestion, ça pourrais presque valoir le coup de faire une méthode à part pour tes erreurs.
Moi je dis ça, je dis rien... 😛

2023-01-19 10:24 UTC, qpic-cgi approved these changes

2023-01-19 10:26 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                    message.reply(new JsonObject().put(Field.STATUS, Field.ERROR).put(Field.MESSAGE, "zimbra.user.not.valid"));
t'aurais un exemple si ca a été fait dans un autre module ?

2023-01-19 10:32 UTC, qpic-cgi commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                    message.reply(new JsonObject().put(Field.STATUS, Field.ERROR).put(Field.MESSAGE, "zimbra.user.not.valid"));
```suggestion
                    private void error(String errMessage, String errI18n, message) {
                          log.error(errMessage);
                          message.reply(new JsonObject().put(Field.STATUS, Field.ERROR).put(Field.MESSAGE, i18n));
                    }
```

2023-01-19 11:02 UTC, qpic-cgi requested changes

2023-01-19 11:02 UTC, qpic-cgi commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                    }
Là je ne comprend pas :S

2023-01-19 11:21 UTC, qperie approved these changes

2023-01-19 11:33 UTC, qpic-cgi approved these changes

2023-01-19 13:56 UTC, BastienBenard approved these changes

2023-01-19 13:56 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/helper/EventBusHelper.java
> +    public static void eventBusError(String errMessage, String errI18n, Message<JsonObject> message) {
```suggestion
    public static void eventBusError(String logMessage, String replayErrorMessage, Message<JsonObject> message) {
```
Lorsque tu nomme tes variables, il ne faut pas que tu te base sur le contexte de ce qui l'utilise. Ici tu as nommé errI18n car la fonction parent va appeler cette méthode avec un variable qui correspond a un i18n. Mais si j'utilise t'as méthode, la variable que je vais fournir ne sera pas forcément un i18n.

2023-01-19 13:56 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/CalendarService.java
> +import io.vertx.core.json.JsonObject;
Est ce utile ?

2023-01-19 14:43 UTC, merged