feat(recall): MZI-160 add actions, tasks and recall_recipient tables
OPEN-ENT-NG/zimbra-connector pull request #61
Opened 2023-01-27 15:48 UTC by aymericdevriesere

## Describe your changes
After new conception, adding all new tables to zimbra schema db
## Checklist tests

## Issue ticket number and link
[ MZI-160 ]
https://jira.support-ent.fr/browse/MZI-160
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-27 15:51 UTC, alicedraillard approved these changes

2023-01-30 13:54 UTC, qpic-cgi approved these changes

2023-01-30 14:02 UTC, Matiyeu requested changes

2023-01-30 14:02 UTC, Matiyeu commented on zimbra/src/main/resources/sql/010-zimbra-action.sql
> +    date     timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
```suggestion
    created_at  timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
```

2023-01-30 16:10 UTC, Matiyeu approved these changes

2023-01-30 17:25 UTC, sjollois approved these changes

2023-01-31 13:10 UTC, closed without merging