feat: #MZI-163 add recall cron + worker
OPEN-ENT-NG/zimbra-connector pull request #63
Opened 2023-01-31 14:41 UTC by Matiyeu

## Describe your changes

add recall cron
add recall base worker
add recall service

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-31 16:30 UTC, alicedraillard approved these changes

2023-02-01 09:05 UTC, JinDouang requested changes

2023-02-01 09:05 UTC, JinDouang commented on zimbra/deployment/zimbra/conf.j2
> +        "recall-cron": {{ zimbraRecallCron | default(' 0 */2 * * * ? *') }},
A rajouter aussi dans le readme avec une explication!

2023-02-01 09:05 UTC, JinDouang commented on zimbra/deployment/zimbra/conf.json.template
> +    "zimbra-recall-cron" : "$zimbraRecallCron",
je comprends pas, tu as 2 configurations différentes ?

c'est quoi "zimbra-call-cron" et "recall-cron" ?

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/cron/RecallMailCron.java
> +        message.put("action", RecallMailWorker.ACTION_REFILL_QUEUE);
magic string

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/cron/RecallMailCron.java
> +        eb.request(RecallMailWorker.RECALL_MAIL_HANDLER_ADDRESS, message, handler -> {
Tu peux peut-être mettre en place un handler pour les messages response (cf exemple : https://github.com/OPEN-ENT-NG/nextcloud/blob/dev/src/main/java/fr/openent/nextcloud/helper/MessageResponseHandler.java#L11)

(à adapter avec asyncResult - pas besoin d'utiliser either)
Comme ça tu pourrais l'appeler comme ça : 

```suggestion
        eb.request(RecallMailWorker.RECALL_MAIL_HANDLER_ADDRESS, message, MessageResponseHandler.messageJsonObjectAsyncHandler(event -> {
             // content
        }));
```

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/model/task/Action.java
> +public class Action {
une raison si la classe n'a pas de contenu ?

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/QueueService.java
> +    Future<List<Task>> getTasksInProgress(TaskType taskType);
java doc si possible sur tes nouvelles méthodes

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/RecallMailService.java
> +public interface RecallMailService {
java doc de tes méthodes si possible

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/QueueServiceImpl.java
> +                promise.fail(result.left().getValue());
log erreur si possible ?

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/QueueServiceImpl.java
> +                promise.fail(result.left().getValue());
log erreur si possible ?

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/QueueServiceImpl.java
> +        return null;
une raison si on retourne null ?

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/RecallMailServiceImpl.java
> +        return null;
une raison si on retourne null pour l'instant ?

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/worker/QueueWorker.java
> +    public static final String ACTION_REMOVE_TASK = "removeTask";
Est-ce qu'ils ont un lien avec ta classe Action ? (la classe qui n'a pas de contenu)

2023-02-01 09:05 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/worker/RecallMailWorker.java
> +        while (this.running) {
Pas sûr que ça soit nécessaire d'avoir une boucle inf ?

2023-02-01 09:07 UTC, Matiyeu commented on zimbra/deployment/zimbra/conf.json.template
> +    "zimbra-recall-cron" : "$zimbraRecallCron",
Même chose, me suis trompé sur le naming, je corrige

2023-02-01 09:15 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/RecallMailServiceImpl.java
> +        return null;
Pas implémenté dans ma PR, je vais throw new NotImplementedException();

2023-02-01 09:15 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/QueueServiceImpl.java
> +        return null;
Pas implémenté dans ma PR, je vais throw new NotImplementedException();

2023-02-07 10:05 UTC, aymericdevriesere approved these changes

2023-02-07 10:05 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/worker/QueueWorker.java
> +    public static final String ACTION_REFILL_QUEUE = "refill";
enum ?

2023-02-07 10:05 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/worker/RecallMailWorker.java
> +        String action = event.body().getString("action", "");
magic string

2023-02-08 15:42 UTC, merged