fix: #MZI-177 improve zimbra request when moving and deleting mails
OPEN-ENT-NG/zimbra-connector pull request #64
Opened 2023-02-02 10:29 UTC by Matiyeu

## Describe your changes

- Created a new method to move messages in Zimbra with batch size of 100
- Created a new method to delete messages in Zimbra with batch size of 100
- Use body to pass id (instead of query params) for this requests : 
  - PUT /zimbra/trash
  - PUT /zimbra/restore
  - DELETE /zimbra/delete
  - PUT /zimbra/move/userfolder/:folderId
  - PUT /zimbra/move/root

> We keep getting param id in URL until the mobile app conforms to it.

## Checklist tests

- [x] Empty trash with more than 100 mails
- [x] Move one or multiple mails in a folder
- [x] Move one or multiple mails in trash

## Issue ticket number and link

[JIRA#MZI-177](https://jira.support-ent.fr/browse/MZI-177)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-02-02 10:33 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                        body.getJsonArray(Field.ID, new JsonArray()).getList();
We keep the backward compatibility for the mobile application

2023-02-02 10:33 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                        body.getJsonArray(Field.ID, new JsonArray()).getList();
We keep the backward compatibility for the mobile application

2023-02-02 10:33 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                        body.getJsonArray(Field.ID, new JsonArray()).getList();
We keep the backward compatibility for the mobile application

2023-02-02 10:33 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                        body.getJsonArray(Field.ID, new JsonArray()).getList();
We keep the backward compatibility for the mobile application

2023-02-02 10:33 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                        body.getJsonArray(Field.ID, new JsonArray()).getList();
We keep the backward compatibility for the mobile application

2023-02-02 10:33 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +    private final int BATCH_SIZE = 100;
Number of emails to send in one batch

2023-02-02 14:05 UTC, BastienBenard reviewed
Il manque la doc d'API dans la description de ta PR

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            JsonObject error = (new JsonObject()).put("error", err.getMessage());
Magic string + Il ne faut pas remonter l'erreur directement a l'utilisateur, car elle peut contenir des info sensible.

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                final List<String> messageIds = body.getJsonArray(Field.ID).getList().isEmpty() ?
NPE avec body.getJsonArray(Field.ID) -> body.getJsonArray(Field.ID, new JsonArray())

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                final List<String> messageIds = body.getJsonArray(Field.ID).getList().isEmpty() ?
same NPE

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            JsonObject error = (new JsonObject()).put("error", err.getMessage());
info sensible.

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                final List<String> messageIds = body.getJsonArray(Field.ID).getList().isEmpty() ?
same NPE

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            Renders.renderJson(request, error, 400);
info sensible.

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                final List<String> messageIds = body.getJsonArray(Field.ID).getList().isEmpty() ?
Same NPE

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            Renders.renderJson(request, error, 400);
info sensible.

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                final List<String> messageIds = body.getJsonArray(Field.ID).getList().isEmpty() ?
Same NPE

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            Renders.renderJson(request, error, 400);
info sensible.

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +    public Future<JsonObject> moveMessagesToFolder(List<String> messageIDs, String folderId, UserInfos user) {
Si tu ne retourne aucun info, autant retourner un Promise\<Void\>

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +    private Future<JsonObject> moveBatchMessageToFolder(List<String> messageIDs, String folderId, UserInfos user) {
Si tu ne retourne aucun info, autant retourner un Promise\<Void\>

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +                        .put("_jsns", SoapConstants.NAMESPACE_MAIL));
Magic String

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +    public Future<JsonObject> deleteMessages(List<String> messageIDs, UserInfos user, boolean trashConstraint) {
Si tu ne retourne aucun info, autant retourner un Promise\<Void\>

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +        }
Tu peux utiliser une dépendance apache pour simplifier ce code. A voir si ça te va.
compile "org.apache.commons:commons-text:1.6"
ListUtils.partition(messageIDs, BATCH_SIZE)

2023-02-02 14:05 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +    private Future<JsonObject> deleteBatchMessages(List<String> messageIDs, UserInfos user, boolean trashConstraint) {
Si tu ne retourne aucun info, autant retourner un Promise\<Void\>

2023-02-03 08:09 UTC, BastienBenard approved these changes

2023-02-03 08:09 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +        }
List<List<String>> batchMessageIds = ArrayHelper.split(messageIDs, BATCH_SIZE).stream()
.map(ids -> this.deleteBatchMessages(ids, user, trashContraint))

2023-02-03 09:05 UTC, sjollois commented
équipe appli mobile à prévenir du changement de ces urls !

2023-02-03 09:35 UTC, sjollois requested changes

2023-02-03 09:35 UTC, sjollois commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            Renders.renderJson(request, error, 400);
Pourquoi il y a deux fois la même route qui fait les mêmes actions !!?? Il faut seulement en garder une des deux

2023-02-03 09:35 UTC, sjollois commented on zimbra/src/main/resources/public/ts/model/http.ts
> +            return http.put(url, data, config);
Là on a l'air de plus attendre la réponse des routes appelés, tu es sur ?

2023-02-03 10:21 UTC, Matiyeu commented on zimbra/src/main/resources/public/ts/model/http.ts
> +            return http.put(url, data, config);
La promesse était await 2 fois, elle est déjà await au moment de l'appel de la fonction

2023-02-03 10:26 UTC, Matiyeu commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            Renders.renderJson(request, error, 400);
Il y en a une qui déplace le mail dans un folderId et l'autre dans INBOX, mais oui je suis d'accord qu'elles pourraient être fusionnées

2023-02-07 15:10 UTC, JinDouang requested changes

2023-02-07 15:10 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            JsonObject error = (new JsonObject()).put(Field.ERROR, err.getMessage());
log error

2023-02-07 15:10 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            JsonObject error = (new JsonObject()).put(Field.ERROR, err.getMessage());
log error

2023-02-07 15:10 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            JsonObject error = (new JsonObject()).put(Field.ERROR, err.getMessage());
log error

2023-02-07 15:10 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            Renders.renderJson(request, error, 400);
log error

2023-02-07 15:10 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +                promise.fail(response.left().getValue());
log.error

2023-02-07 15:10 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +                .onFailure(err -> promise.fail(err.getMessage()));
log.error

2023-02-07 15:10 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +                .onFailure(err -> promise.fail(err.getMessage()));
log.error

2023-02-07 15:10 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +                promise.fail(response.left().getValue());
log.error

2023-02-08 09:48 UTC, Matiyeu commented
Commit cherry pick for hotfix 2.9.4

2023-02-08 09:48 UTC, closed without merging