feat(recall): MZI-187 fetch recalled mails from db
OPEN-ENT-NG/zimbra-connector pull request #72
Opened 2023-02-21 14:41 UTC by aymericdevriesere

## Describe your changes
Add all classes and logic needed to request database and retrieve recallTasks.
This PR is part of the update how do we manage recall mail.
## Checklist tests

## Issue ticket number and link
[ MZI-187 ]
https://jira.support-ent.fr/browse/MZI-187
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-02-24 16:33 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/data/sqlTaskServices/SqlRecallTaskService.java
> +    public Future<JsonArray> retrieveTasksDataFromDB(TaskStatus status) {
Tu peux utiliser des model en retournant une Future\<List\<RecallTask\>\>

2023-02-24 16:33 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/data/sqlTaskServices/SqlRecallTaskService.java
> +    public Future<JsonObject> createTask(Action<RecallTask> action, RecallTask task) {
Tu peux utiliser des model en retournant une Future\<<RecallTask\>

2023-02-27 08:09 UTC, JinDouang requested changes

2023-02-27 08:09 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/data/sqlTaskServices/SqlRecallTaskService.java
> +                .append("WHERE recall_tasks.status = ?;");
Avec StringBuilder, qu'est-ce que tu utilises de plus hormis `.append` ? 
Si tu n'as pas d'autres usage (`insert`, `reverse` etc...) selon moi il vaut mieux utiliser un String normal : 

```suggestion
 String query = "SELECT * " +
                this.taskTable + " as recall_tasks " +
                "JOIN " + this.actionTable + " as actions" + " on actions.id = recall_tasks.action_id" +
                "JOIN " + this.recallMailTable + " as recall_mails" + " on actions.id = recall_mails.action_id " +
                "WHERE recall_tasks.status = ?;";
```

2023-02-27 08:09 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/data/sqlTaskServices/SqlRecallTaskService.java
> +        query.append("INSERT INTO ")
cf commentaire

2023-02-27 08:31 UTC, JinDouang approved these changes

2023-02-27 08:54 UTC, BastienBenard approved these changes

2023-02-27 09:05 UTC, alicedraillard approved these changes

2023-02-27 09:07 UTC, merged