feat(recall): #MZI-168 modify recall mail logic
OPEN-ENT-NG/zimbra-connector pull request #84
Opened 2023-03-28 08:16 UTC by aymericdevriesere

## Describe your changes
Redefine the flow when recalling a mail using models, services and helpers.
API Recall doc: https://confluence.support-ent.fr/display/ZIM/Messages
Changes :
  - Retrieve adml for recall mail is now done in one request
  - Change method for retrieving ids
  - Use model for users, messages and recall mail

## Checklist tests
- Recall a mail: mail is inserted in database, and admls are notified
## Issue ticket number and link
[ MZI-168 ]
https://jira.support-ent.fr/browse/MZI-168
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-28 08:18 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/Zimbra.java
> +//        vertx.deployVerticle(RecallMailWorker.class.getName(), new DeploymentOptions().setWorker(true).setConfig(config));
feature will be available in next dev step

2023-03-28 08:19 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/helper/TransactionHelper.java
> +package fr.openent.zimbra.helper;
Code from CRRE

2023-03-28 08:19 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/model/TransactionElement.java
> +package fr.openent.zimbra.model;
Code from CRRE

2023-03-28 14:19 UTC, BastienBenard reviewed
Il manque les tests sur les différents services

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +    @SecuredAction(value = "zimbra.recall.right", type = ActionType.WORKFLOW)
il manque la doc d'API

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +            RequestUtils.bodyToJson(request, body -> {
Tu peux mettre un jsonschema pour vérifier que ton body est correcte

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +//                            returnedMailService.renderReturnedMail(request, user, event);
tu réponds pas a la request ?

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/helper/MessageHelper.java
> +    static RecipientService recipientService = ServiceManager.getServiceManager().getRecipientService();
ça sert ?

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/helper/TaskHelper.java
> +        Iterator<JsonObject> recallTaskIterator = tasksData.stream().filter(taskData -> taskData instanceof JsonObject).map(JsonObject.class::cast).iterator();
filter(JsonObject.class::isInstance)

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/helper/TaskHelper.java
> +    public static List<RecallTask> convertJsonListToTask(Action<RecallTask> action, JsonArray tasksData) {
A voir pour lever une exception

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/model/EntUser.java
> +                .map(structUai -> new Structure(null, null, (String) structUai))
.map(String.class::cast)

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/DbTaskService.java
> +    public abstract Future<JsonArray> createTasksByBatch(Action<RecallTask> action, List<RecallTask> tasks, int batchSize);
Tu peux retourner une future de list de T non ?

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/data/Neo4jZimbraService.java
> +		params.put("structuresId", structuresId);
Magic string

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/UserService.java
> +                            .stream().filter(adml -> (adml instanceof JsonObject) && EntUserHelper.JSONContainsADMLData((JsonObject) adml))
filter(JsonObject.class::isInstance)
.map(JsonObject.class::cast)
.filter(adml -> EntUserHelper.JSONContainsADMLData(adml))

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/UserService.java
> +                                JsonObject data = (JsonObject) adml;
pas de cast ici du coup

2023-03-28 14:19 UTC, BastienBenard commented on zimbra/src/main/java/fr/openent/zimbra/worker/ICalRequestWorker.java
> +        //todo
Todo ?

2023-03-30 12:22 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/worker/ICalRequestWorker.java
> +        //todo
prochaine pr

2023-03-30 12:24 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +//                            returnedMailService.renderReturnedMail(request, user, event);
prochaine pr est axée sur ce dev

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/data/Neo4jZimbraService.java
> +	public void listAdml(List<String> structuresId, Handler<Either<String, JsonArray>> result) {
y'a un TU dessus ?

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/RecipientService.java
> +                promise.fail("error.retrieving.ids");
Enum pour les erreurs (existe déjà --> errorEnum)

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/RecipientService.java
> +                promise.fail("error.retrieving.ids");
a faire pour tous tes promise.fail btw

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/StructureServiceImpl.java
> +                            promise.fail("error.fetching.admls");
errorEnum

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/UserService.java
> +                            }).collect(Collectors.toList()));
retour à la ligne

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/UserService.java
> +                                JsonHelper.getStringList(adml.getJsonArray(Field.STRUCTURES));
default value pour le getJsonArray

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/UserService.java
> +                    promise.fail("error.retrieving.admls");
errorEnum

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/StructureServiceImpl.java
> +                                        return new Structure(struct.getString(Field.STRUCTURE)).setADMLS(JsonHelper.getStringList(struct.getJsonArray(Field.ADMLS)));
default value pour le get

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/QueueService.java
> +                        promise.fail("zimbra.error.queue.task");
errorENum

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/QueueService.java
> +                    promise.fail("zimbra.error.queue.task");
idem

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/QueueService.java
> +            return Future.failedFuture("no.mail.to.recall");
errorEnum

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/QueueService.java
> +                        promise.fail("zimbra.error.queue.task");
idem

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/QueueService.java
> +                    promise.fail("zimbra.error.task.retrieve");
idem

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/QueueService.java
> +                            promise.fail("zimbra.error.editing.task");
idem (jte laisse faire la mm pr le reste du fichier)

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/RecallMailServiceImpl.java
> +                    promise.fail("error.fetching.ids");
errorEnum etc pr le reste du fichier

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/RecallMailServiceImpl.java
> +                                notificationService.sendReturnMailNotification(user, mail.getMessage().getSubject(), structure.getId(), structure.getADMLS(), null, event -> {})
c'est normal le handler vide event->{} ?

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/RecallMailServiceImpl.java
> +    public Future<Void> deleteMessage (String recallMailId) {
utile ?

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/RecallQueueServiceImpl.java
> +            return Future.failedFuture("no.mail.to.recall");
errorEnum

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/data/SqlRecallMailService.java
> +                        recallMail.setId(recallData.getInteger(Field.ID));
default value pr le get

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/data/SqlRecallMailService.java
> +                        promise.fail("zimbra.fail.create.recall");
errorEnum

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/data/SqlRecallMailService.java
> +                    promise.fail("zimbra.fail.create.recall");
errorEnum

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/data/SqlRecallTaskService.java
> +                    promise.fail("zimbra.error.queue.task");
errorEnum

2023-03-30 13:22 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +    @SecuredAction(value = "zimbra.recall.right", type = ActionType.WORKFLOW)
pourquoi pas "zimbra.recall" ? on sait déjà que c'est un droit

2023-03-30 13:34 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/RecallMailServiceImpl.java
> +    public Future<Void> deleteMessage (String recallMailId) {
sera fait dans la prochaine pr c etait pour pas l'oublier

2023-03-30 15:49 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/service/data/Neo4jZimbraService.java
> +	public void listAdml(List<String> structuresId, Handler<Either<String, JsonArray>> result) {
yes

2023-03-31 08:04 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/helper/TaskHelper.java
> +    public static List<RecallTask> convertJsonListToTask(Action<RecallTask> action, JsonArray tasksData) throws Exception {
--> nommage :  l'appeler convertJsonArrayToTaskList serait + clair
--> faire une classe abstraite pr le TaskHelper + un RecallTaskHelper

2023-03-31 08:14 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/StructureServiceImpl.java
> +                                                        .setADMLS(JsonHelper.getStringList(struct.getJsonArray(Field.ADMLS))))
default values pour les get, surtout le getJsonArray et getStringlist

2023-03-31 08:14 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/QueueService.java
> +    protected abstract List<T> createTasksFromData(Action<T> action, JsonArray taskData) throws Exception;
java doc

2023-03-31 08:14 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/data/SqlRecallMailService.java
> +                        recallMail.setId(recallData.getInteger(Field.ID));
?

2023-03-31 08:14 UTC, alicedraillard commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/data/SqlRecallTaskService.java
> +    private TransactionElement createTransactionForTasks(Action<RecallTask> action, List<RecallTask> tasks) {
java doc

2023-03-31 08:14 UTC, alicedraillard commented on zimbra/src/main/resources/jsonschema/recallMail.json
> +{
c'est utilisé ou ?

2023-03-31 08:44 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/StructureServiceImpl.java
> +                                                        .setADMLS(JsonHelper.getStringList(struct.getJsonArray(Field.ADMLS))))
c'est dans un try, si un truc fail, on renvoie une erreur

2023-03-31 08:59 UTC, aymericdevriesere commented on zimbra/src/main/resources/jsonschema/recallMail.json
> +{
Dans le controller pour être sur que tu récup ce que tu veux du body (dans la fonction recallMail, pour la route /recall)

2023-03-31 09:36 UTC, alicedraillard approved these changes

2023-03-31 12:56 UTC, JinDouang requested changes

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/controllers/ZimbraController.java
> +                            .onSuccess(res -> renderJson(request, new JsonObject().put(Field.STATUS, "SUCCESS")))
magic string SUCCESS

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/helper/EntUserHelper.java
> +    public static boolean JSONContainsADMLData(JsonObject ADMLData) {
Mets un constructeur pour pas le rendre instanciable si ca a pour but d'être static (https://rules.sonarsource.com/java/rspec-1118/)

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/helper/EntUserHelper.java
> +    public static boolean JSONContainsADMLData(JsonObject ADMLData) {
Renomme ta fonction et param en camelCase etc (https://rules.sonarsource.com/java/RSPEC-117)

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/security/RecallFilter.java
> +        }
Possibilité de faire en une ligne sans passer par if - else ?

```suggestion
        handler.handle(WorkflowActionUtils.hasRight(user, WorkflowActions.RECALL_RIGHT.toString()));
```

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/RecipientService.java
> +                String errMessage = String.format("[Zimbra@%s::getUseridsFromEmails]:  " +
Il faudrait aussi mettre l'erreur `list.cause().getMessage()` dans ton string.format

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/StructureServiceImpl.java
> +import fr.openent.zimbra.helper.StructureHelper;
import non utilisé

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/StructureServiceImpl.java
> +import io.vertx.core.json.JsonObject;
import non utilisé

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/StructureServiceImpl.java
> +import java.util.stream.Collectors;
import non utilisé

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/UserService.java
> +import java.util.stream.Collectors;
import non utilisé

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/DbActionService.java
> +    public DbActionService(String schema) {
protected non ?

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/DbTaskService.java
> +    public DbTaskService(String schema) {
protected non?

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/DbTaskService.java
> +import fr.openent.zimbra.model.task.ICalTask;
Pas utilisé

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/RecallMailServiceImpl.java
> +    public static ConfigManager appConfig;
J'ai l'impression que tu ne l'utilises pas, une raison de le garder ?

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/RecallMailServiceImpl.java
> +    private final static int BATCH_SIZE = 100;
static avant final dans la convention de java

```suggestion
    private static final int BATCH_SIZE = 100;
```

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/data/SqlActionService.java
> +        StringBuilder query = new StringBuilder();
Quel intérêt pour ce cas là d'utiliser StringBuilder à faire les `append` ? Vaut mieux rester en String si tu ne fais pas d'autre opération comme replace, revert etc...

surtout que tu concat dans ton RETURNING donc...

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/data/SqlRecallMailService.java
> +    private static Logger log = LoggerFactory.getLogger(SqlRecallMailService.class);
Il peut être final

```suggestion
    private static final Logger log = LoggerFactory.getLogger(SqlRecallMailService.class);
```

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/tasks/service/impl/data/SqlRecallTaskService.java
> +    private static Logger log = LoggerFactory.getLogger(SqlRecallTaskService.class);
idem 
```suggestion
    private static final Logger log = LoggerFactory.getLogger(SqlRecallTaskService.class);
```

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/worker/QueueWorker.java
> +        int maxQueueSize = event.body().getInteger(Field.MAXQUEUESIZE, configManager.getZimbraRecallWorkerMaxQueue());
Attention je constate que le nommage de ta variable est la même que celle ligne 31, à changer si possible

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/worker/QueueWorker.java
> +            case REMOVE_TASK:
Attention, le fait que tu ne break pas dans ton try / catch, tu vas forcer tous les statement à s'exécuter

A moins que ça soit un choix volontaire de tout exécuter ??

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/worker/QueueWorker.java
> +            if (!this.queue.contains(taskIteration) && (this.queue.size() < this.maxQueueSize)) {
Potentiel problème de consistance sur ta collection `T` : https://rules.sonarsource.com/java/RSPEC-2175

Exemple de pb : https://community.sonarsource.com/t/java-s2175-using-number-as-key-type-in-a-map-produces-false-positives-when-int-is-used-when-accessing-the-map-value/32022

tu risques d'avoir un NPE

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/worker/QueueWorker.java
> +    };
pourquoi ; ?

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/worker/QueueWorker.java
> +        response.put(Field.STATUS, 200);
je sais que tu ne l'as pas modifié donc proposition : https://github.com/scalatra/netty-extension/blob/master/src/main/java/org/jboss/netty/handler/codec/http2/HttpResponseStatus.java

au lieu de 200 en magic number ^^

2023-03-31 12:56 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/worker/QueueWorker.java
> +        response.put(Field.STATUS, 200);
idem

2023-03-31 14:22 UTC, JinDouang approved these changes

2023-03-31 14:25 UTC, merged