fix(recall): #MZI-226 delay task execution
OPEN-ENT-NG/zimbra-connector pull request #94
Opened 2023-07-10 08:23 UTC by aymericdevriesere

## Describe your changes
Context: 
To recall mail to different recipient, we treat it as tasks. Each recipient is a task and the task is execute in a queue as FIFO. We noticied that zimbra server struggled to handle too many request at the same time, especially when the recipient remains the same.
Solution:
Now the queue will wait for the previous task to complete before executing the new one.
## Checklist tests
- [x] Recall 20 mails to the same sender
## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-07-10 15:04 UTC, qperie approved these changes

2023-07-11 06:45 UTC, JinDouang requested changes

2023-07-11 06:45 UTC, JinDouang commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +                    String query = "* msgid:\"" + msgid + "\"";
Peux-tu préciser la raison de cette modification de la query ?

Pense également à maj le commentaire comme c'est obsolète

2023-07-11 15:04 UTC, aymericdevriesere commented on zimbra/src/main/java/fr/openent/zimbra/service/impl/MessageService.java
> +                    String query = "* msgid:\"" + msgid + "\"";
les reste n est pas pertinent pour trouver le message, donc laisser des éléments non essentiels introduit des risques d'erreurs

2023-07-11 16:01 UTC, JinDouang approved these changes

2023-07-12 07:52 UTC, merged